### PR TITLE
ODPM-65 - Provide census data if available via agency API

### PR DESCRIPTION
**Pull request by trawick**
Importing the data will populate agency tables with census GEOID values when present in `{MD,NC}_agencies.csv`.

The agency API will return a dictionary of census data with the same racial and ethnic breakdowns as in `census.temporary.json`.  Source of census data is not provided.  (The front-end code currently
ignores the year from `census.temporary.json` anyway.)

`NC_agencies.csv` covers all of the small number of locales in `census.temporary.json` other than "Charlotte-Mecklenburg Police Department".

Future (after this pull request):
- front-end changes to use the new API (and remove  `census.temporary.json`)
- what census source to show on front-end for census data?

### CODE REVIEW

**Comment by copelco** [comment]
Description seems correct to me. We should bring up Charlotte PD with Ian at the meeting today.

**Comment by rlconley** [comment]
When I run this code (even after running migrations) but before running an import I get this error:
`Internal Server Error: /md/agency/
Traceback (most recent call last):
  File "/home/rlconley/.virtualenvs/opendatapolicing/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column md_agency.census_profile_id does not exist`

**Comment by trawick** [comment]
> `column md_agency.census_profile_id does not exist`

Perhaps you didn't run migrations against all three databases?

I also see the missing tsdata migration.  As it isn't caused by this pull request and isn't harmful, I thought I'd handle it separately along with adding a sanity check to testing to ensure that no migrations need to be generated.

**Comment by copelco** [comment]
Both NC and MD imports worked locally for me 👍

**Comment by rlconley** [comment]
@trawick is right. I didn't pass a db into showmigrations. Did they run on the default? Yes. Did they run on the states? No.

**Pull request merged**
