### PR TITLE
ODPM-198 - Upgrade Margarita for newer Lets Encrypt code

### PR DESCRIPTION
**Pull request by trawick**
This included rebasing the customized db/init.sls file based on the latest Margarita version.

A deployment has been made to staging using this branch, though the new NC agency is not effective yet since that comes from the Git checkout.

Also:

- update keys files with current developers
- add new NC agency "Forest City Police Department"

Manual configuration/deploy steps for putting this on production:

1. the root cron job to renew the certificate didn't work until this was added:
```
PATH=/usr/bin:/bin:/sbin:/usr/local/bin
```
2. Step "v" of the Margarita/Salt upgrade steps at https://github.com/caktus/margarita/blob/develop/CHANGES.rst#v-200-on-december-15-2016 need to be performed for production.

~~The Travis test may fail like this: https://travis-ci.org/OpenDataPolicingNC/Traffic-Stops/builds/240774627
I don't know what that is about or how these changes could conceivably trigger that.~~

### CODE REVIEW

**Comment by jbradberry** [comment]
@trawick I think because of this line of the output (https://travis-ci.org/OpenDataPolicingNC/Traffic-Stops/builds/240774627#L929) that the `SYSLOG_PATH` is getting set to `None` (https://github.com/OpenDataPolicingNC/Traffic-Stops/blob/ff255dbc2c8dccda8e329ed2332c16201510e17c/traffic_stops/settings/base.py#L202-L205).  Perhaps if we change settings/dev.py to knock out the syslog logger, or change settings/base.py to not include it if `SYSLOG_PATH` winds up as `None`?

**Comment by jbradberry** [comment]
I have no further comments, so if one of my suggested fixes works quickly, :+1:

**Comment by trawick** [comment]
* The logging issue seen by Travis doesn't cause the build to fail; it is tracked by ODPM-30.  I updated that ticket with the note above from @jbradberry .
* I opened ODPM-199 for the JavaScript test issue that is the cause of the Travis build failure.  I don't believe that it is a blocker for this pull request.

**Comment by jbradberry** [comment]
@trawick agreed :+1:

**Comment by trawick** [comment]
The JS test failure on Travis was resolved with #207 :)

**Pull request merged**
